#!/bin/bash
echo "=== HƯỚNG DẪN KIỂM TRA SERVER LOGS ==="
echo ""
echo "1. Tìm terminal đang chạy 'npm run dev'"
echo "   - Terminal này sẽ hiển thị tất cả logs"
echo ""
echo "2. Hoặc chạy lệnh sau để xem process đang chạy:"
ps aux | grep -E "node|npm" | grep -v grep
echo ""
echo "3. Để chạy server trong terminal riêng:"
echo "   cd '/Users/admin/Desktop/Nhà trọ'"
echo "   npm run server"
echo ""
echo "4. Các logs quan trọng cần tìm:"
echo "   - 'Error' hoặc 'error'"
echo "   - 'Database is null'"
echo "   - 'Error fetching'"
echo "   - 'Error stack'"
echo ""
